class StatusCode:
    SUCCCESS = 200
    POST_SUCCESS = 201
    ERROR = 400
    AUTHORIZATION_ERROR = 401
    CERTIFICATION_ERROR = 403
    NOT_FOUND_ERROR = 404
    DUPLICATION_ERROR = 409
    SERVER_ERROR = 500


class Permission:
    FOLLOW = 1
    COMMENT = 2
    POST = 4
    MODERATE = 8
    ADMIN = 16
